# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "python:3.11-slim"
    id: deploy-data-ingestion-pipeline-staging
    entrypoint: bash
    args:
      - -c
      - |
        cd data_ingestion && pip install uv --user && uv sync --frozen && \
        uv run python data_ingestion_pipeline/submit_pipeline.py
    env:
      - "PIPELINE_ROOT=${_PIPELINE_GCS_ROOT}"
      - "REGION=${_REGION}"
      - "DATA_STORE_REGION=${_DATA_STORE_REGION}"
      - "DATA_STORE_ID=${_DATA_STORE_ID}"
      - "PROJECT_ID=${_STAGING_PROJECT_ID}"
      - "SERVICE_ACCOUNT=${_PIPELINE_SA_EMAIL}"
      - "PIPELINE_NAME=${_PIPELINE_NAME}"
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'
      
  - name: "python:3.11-slim" 
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv --user && uv sync --frozen
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  - name: "python:3.11-slim"
    id: deploy-staging
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "$_FIREBASE_KEY_JSON" > firebase-key.json
        uv export --no-hashes --no-header --no-emit-project --frozen > .requirements.txt
        uv run app/agent_engine_app.py \
          --project ${_STAGING_PROJECT_ID} \
          --location ${_REGION} \
          --set-env-vars "COMMIT_SHA=${COMMIT_SHA},DATA_STORE_ID=${_DATA_STORE_ID},DATA_STORE_REGION=${_DATA_STORE_REGION},SQL_HOST=34.31.4.1,SQL_USER=genai_user,SQL_PASSWORD=ppPP00))pp,SQL_DATABASE=genai_db"
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'
    secretEnv: ['_FIREBASE_KEY_JSON']


  - name: gcr.io/cloud-builders/gcloud
    id: fetch-auth-token
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $(gcloud auth print-access-token -q) > auth_token.txt

  # Load Testing
  - name: "python:3.11-slim"
    id: load_test
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        export _AUTH_TOKEN=$(cat auth_token.txt)
        uv add locust==2.32.6 gevent==24.11.1
        uv run locust -f tests/load_test/load_test.py \
        --headless \
        -t 15s -u 1 -r 0.25 \
        --csv=tests/load_test/.results/results \
        --html=tests/load_test/.results/report.html
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # Export Load Test Results to GCS
  - name: gcr.io/cloud-builders/gcloud
    id: export-results-to-gcs
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        export _TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        gsutil -m cp -r tests/load_test/.results gs://${_BUCKET_NAME_LOAD_TEST_RESULTS}/results-$${_TIMESTAMP}
        echo "_________________________________________________________________________"
        echo "Load test results copied to gs://${_BUCKET_NAME_LOAD_TEST_RESULTS}/results-$${_TIMESTAMP}"
        echo "HTTP link: https://console.cloud.google.com/storage/browser/${_BUCKET_NAME_LOAD_TEST_RESULTS}/results-$${_TIMESTAMP}"
        echo "_________________________________________________________________________"

  # Trigger Prod Deployment
  - name: gcr.io/cloud-builders/gcloud
    id: trigger-prod-deployment
    entrypoint: gcloud
    args:
      - "beta"
      - "builds"
      - "triggers"
      - "run"
      - "deploy-to-prod-pipeline"
      - "--region"
      - "$LOCATION"
      - "--project"
      - "$PROJECT_ID"
      - "--sha"
      - $COMMIT_SHA

  - name: gcr.io/cloud-builders/gcloud
    id: echo-view-build-trigger-link
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "_________________________________________________________________________"
        echo "Production deployment triggered. View progress and / or approve on the Cloud Build Console:"
        echo "https://console.cloud.google.com/cloud-build/builds;region=$LOCATION"
        echo "_________________________________________________________________________"

  - name: "gcr.io/cloud-builders/docker"
    id: build-react-image
    args:
      - build
      - "-t"
      - "gcr.io/${PROJECT_ID}/kene-frontend-staging:${COMMIT_SHA}"
      - "-f"
      - "frontend/Dockerfile"
      - "--build-arg"
      - "VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}"
      - "--build-arg"
      - "VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "VITE_API_BASE_URL=${_VITE_API_BASE_URL}"
      - "--build-arg"
      - "VITE_RECAPTCHA_SITE_KEY=${_RECAPTCHA_SITE_KEY_STAGING}"
      - "./frontend"

  - name: "gcr.io/cloud-builders/docker"
    id: push-react-image
    args:
      - push
      - "gcr.io/${PROJECT_ID}/kene-frontend-staging:${COMMIT_SHA}"

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-react-cloud-run
    args:
      - "run"
      - "deploy"
      - "kene-frontend-staging"
      - "--image=gcr.io/${PROJECT_ID}/kene-frontend-staging:${COMMIT_SHA}"
      - "--region=${_REGION}"
      - "--allow-unauthenticated"
      - "--memory=1Gi"
      - "--project=${_STAGING_PROJECT_ID}"

  - name: "gcr.io/cloud-builders/docker"
    id: build-api-image
    dir: api
    args:
      - build
      - "-t"
      - "gcr.io/${PROJECT_ID}/kene-api-staging:${COMMIT_SHA}"
      - "-f"
      - "Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: push-api-image
    args:
      - push
      - "gcr.io/${PROJECT_ID}/kene-api-staging:${COMMIT_SHA}"

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-api-to-cloud-run
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
          set -e
          set -x

          echo "Deploying Cloud Run service with attached service account..."
          gcloud run deploy kene-api-staging \
            --image=gcr.io/${PROJECT_ID}/kene-api-staging:${COMMIT_SHA} \
            --region=${_REGION} \
            --platform=managed \
            --project=${_STAGING_PROJECT_ID} \
            --allow-unauthenticated \
            --memory=512Mi \
            --port=8000 \
            --service-account=${_API_SERVICE_ACCOUNT_EMAIL} \
            --clear-secrets \
            --set-env-vars "DEBUG=false,HOST=0.0.0.0,NEO4J_URI=${_NEO4J_URI},NEO4J_USERNAME=${_NEO4J_USERNAME},NEO4J_PASSWORD=${_NEO4J_PASSWORD},NEO4J_DATABASE=${_NEO4J_DATABASE},AURA_INSTANCEID=${_AURA_INSTANCEID},AURA_INSTANCENAME=${_AURA_INSTANCENAME},SUPERSET_BASE_URL=${_SUPERSET_BASE_URL},SUPERSET_USERNAME=${_SUPERSET_USERNAME},SUPERSET_PASSWORD=${_SUPERSET_PASSWORD},GOOGLE_CLOUD_PROJECT_ID=${_STAGING_PROJECT_ID},FIRESTORE_DATABASE_ID=(default),LOG_LEVEL=INFO,USE_APPLICATION_DEFAULT_CREDENTIALS=true,RECAPTCHA_SITE_KEY=${_RECAPTCHA_SITE_KEY_STAGING},RECAPTCHA_SECRET_KEY=${_RECAPTCHA_SECRET_KEY_STAGING}"



substitutions:
  _STAGING_PROJECT_ID: ken-e-staging
  _BUCKET_NAME_LOAD_TEST_RESULTS: ${PROJECT_ID}-cicd-load-test-results
  _REGION: us-central1
  _DATA_STORE_REGION: us
  _PIPELINE_NAME: genai_sample_data_ingestion
  _NEO4J_DATABASE: neo4j
  _NEO4J_URI: neo4j+s://f7649bfa.databases.neo4j.io
  _NEO4J_USERNAME: neo4j
  _NEO4J_PASSWORD: ***REMOVED***
  _AURA_INSTANCEID: f7649bfa
  _AURA_INSTANCENAME: KEN-E Staging
  _SUPERSET_BASE_URL: https://superset.ken-e.ai
  _SUPERSET_USERNAME: api
  _SUPERSET_PASSWORD: ***REMOVED***
  _VITE_FIREBASE_API_KEY: AIzaSyC2Oxqfs3AxCcggkrS-rZxepvP2onV7lOI
  _VITE_FIREBASE_AUTH_DOMAIN: ken-e-staging.firebaseapp.com
  _VITE_API_BASE_URL: https://kene-api-staging-391472102753.us-central1.run.app
  _API_SERVICE_ACCOUNT_EMAIL: ken-e-api@ken-e-staging.iam.gserviceaccount.com
  _RECAPTCHA_SITE_KEY_STAGING: ${_RECAPTCHA_SITE_KEY_STAGING}
  _RECAPTCHA_SECRET_KEY_STAGING: ${_RECAPTCHA_SECRET_KEY_STAGING}

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/firebase-key-staging/versions/latest
      env: _FIREBASE_KEY_JSON