/**
 * Simulation Recommendation Types & Mock Data
 *
 * Each recommendation represents one of three actions:
 *   - add: A new activity the user should add to the Campaign Calendar
 *   - modify: An existing activity that should be changed
 *   - delete: An existing activity that should be removed
 */

import type { CalendarActivity, FunnelObjective } from './calendarData';

export type RecommendationAction = 'add' | 'modify' | 'delete';

export interface RecommendationImpact {
  metric: string;
  changePercent: number;
}

interface BaseRecommendation {
  id: string;
  action: RecommendationAction;
  rationale: string;
  funnelStage: FunnelObjective;
  estimatedImpact: RecommendationImpact;
}

export interface AddRecommendation extends BaseRecommendation {
  action: 'add';
  proposedActivity: CalendarActivity;
}

export interface ModifyRecommendation extends BaseRecommendation {
  action: 'modify';
  activityId: string;
  changes: Partial<CalendarActivity>;
  originalValues: Partial<CalendarActivity>;
}

export interface DeleteRecommendation extends BaseRecommendation {
  action: 'delete';
  activityId: string;
  activitySnapshot: CalendarActivity;
}

export type SimulationRecommendation =
  | AddRecommendation
  | ModifyRecommendation
  | DeleteRecommendation;

export type RecStatus = 'pending' | 'accepted' | 'rejected';

// ─── Mock Recommendations ───

export const MOCK_RECOMMENDATIONS: SimulationRecommendation[] = [
  // ADD: New Paid Search pulse for Consideration in April
  {
    id: 'rec-1',
    action: 'add',
    rationale:
      'The model detects a gap in Consideration-stage paid search activity during April. Adding a targeted Google Ads pulse would capitalize on the Brand Awareness momentum built in March and bridge mid-funnel intent to conversion.',
    funnelStage: 'Consideration',
    estimatedImpact: { metric: 'Consideration Volume', changePercent: 12.3 },
    proposedActivity: {
      activity_id: 'act-rec-new-1',
      name: 'Google Ads Consideration Pulse - April',
      campaign_id: 'cc-4',
      channel: 'Paid Search',
      platform: 'Google Ads',
      cost: 4500,
      launch_date: new Date(2026, 3, 14),
      launch_time_utc: '08:00',
      category: 'task',
      task_type: 'Demand Gen',
      tags: ['retargeting', 'enterprise'],
      owner: 'sarah.chen@example.com',
      status: 'Draft',
      created_date: new Date(2026, 2, 25),
      created_by: 'system',
      last_updated_at: new Date(2026, 2, 25),
      last_updated_by: 'system',
    },
  },
  // ADD: Email nurture for Conversion in May
  {
    id: 'rec-2',
    action: 'add',
    rationale:
      'Historical data shows strong email engagement among users who viewed product pages in prior months. A targeted MailChimp nurture sequence in May would convert high-intent leads generated by the Spring Promo campaign.',
    funnelStage: 'Conversion',
    estimatedImpact: { metric: 'Conversions', changePercent: 8.7 },
    proposedActivity: {
      activity_id: 'act-rec-new-2',
      name: 'MailChimp Conversion Nurture - May',
      campaign_id: 'cc-7',
      channel: 'Email',
      platform: 'MailChimp',
      cost: 1200,
      launch_date: new Date(2026, 4, 5),
      launch_time_utc: '07:00',
      category: 'task',
      task_type: 'Demand Gen',
      tags: ['enterprise', 'case-study'],
      owner: 'priya.patel@example.com',
      status: 'Draft',
      created_date: new Date(2026, 2, 25),
      created_by: 'system',
      last_updated_at: new Date(2026, 2, 25),
      last_updated_by: 'system',
    },
  },
  // MODIFY: Increase budget on act-06 (Google Ads Spring Promo)
  {
    id: 'rec-3',
    action: 'modify',
    activityId: 'act-06',
    rationale:
      'The Spring Promo Google Ads activity is currently under-budgeted relative to its conversion efficiency. The model estimates that increasing spend from $15,000 to $19,500 would yield diminishing but still positive marginal returns, with the optimal inflection point near $20k.',
    funnelStage: 'Conversion',
    estimatedImpact: { metric: 'Conversions', changePercent: 15.2 },
    originalValues: {
      cost: 15000,
    },
    changes: {
      cost: 19500,
    },
  },
  // MODIFY: Shift launch date on act-13 (Programmatic Competitive Displacement)
  {
    id: 'rec-4',
    action: 'modify',
    activityId: 'act-13',
    rationale:
      'Moving the Programmatic Competitive Displacement launch from April 5 to April 12 aligns it with a detected competitor quiet period, increasing share-of-voice during a window of reduced competitive noise. The model also suggests increasing budget slightly for maximum impact.',
    funnelStage: 'Consideration',
    estimatedImpact: { metric: 'Consideration Volume', changePercent: 9.1 },
    originalValues: {
      launch_date: new Date(2026, 3, 5),
      cost: 9500,
    },
    changes: {
      launch_date: new Date(2026, 3, 12),
      cost: 11000,
    },
  },
  // DELETE: Remove act-07 (Bing Ads Enterprise Pipeline Accelerator)
  {
    id: 'rec-5',
    action: 'delete',
    activityId: 'act-07',
    rationale:
      'The Bing Ads Enterprise Pipeline Accelerator shows consistently low ROI in the model — the expected direction is "Decrease" and the $3,500 budget generates minimal incremental conversions. Reallocating this spend to Google Ads or Email channels would yield 3-4x better returns.',
    funnelStage: 'Conversion',
    estimatedImpact: { metric: 'ROI Efficiency', changePercent: 18.5 },
    activitySnapshot: {
      activity_id: 'act-07',
      name: 'Bing Ads Enterprise Pipeline Accelerator - Demand Gen',
      campaign_id: 'cc-7',
      channel: 'Paid Search',
      platform: 'Bing Ads',
      cost: 3500,
      launch_date: new Date(2026, 2, 24),
      launch_time_utc: '16:00',
      category: 'task',
      task_type: 'Demand Gen',
      tags: ['enterprise'],
      owner: 'alex.rivera@example.com',
      status: 'Approved',
      created_date: new Date(2026, 2, 17),
      created_by: 'alex.rivera@example.com',
      last_updated_at: new Date(2026, 2, 21),
      last_updated_by: 'emma.thompson@example.com',
    },
  },
  // DELETE: Remove act-11 (Google Display Spring Promo)
  {
    id: 'rec-6',
    action: 'delete',
    activityId: 'act-11',
    rationale:
      'Display retargeting for the Spring Promo is redundant with the higher-performing Google Ads Paid Search activity (act-06). The model shows minimal incremental lift from Display at this budget level. Consolidating spend into Paid Search or Email would improve overall campaign efficiency.',
    funnelStage: 'Conversion',
    estimatedImpact: { metric: 'Cost Efficiency', changePercent: 22.0 },
    activitySnapshot: {
      activity_id: 'act-11',
      name: 'Google Display Spring Promo 2026 - Seasonal',
      campaign_id: 'cc-6',
      channel: 'Display',
      platform: 'Google Display',
      cost: 6000,
      launch_date: new Date(2026, 2, 25),
      launch_time_utc: '09:00',
      category: 'task',
      task_type: 'Seasonal',
      tags: ['promo', 'retargeting'],
      owner: 'sarah.chen@example.com',
      status: 'Approved',
      created_date: new Date(2026, 2, 18),
      created_by: 'sarah.chen@example.com',
      last_updated_at: new Date(2026, 2, 22),
      last_updated_by: 'emma.thompson@example.com',
    },
  },
];