# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

retrieve_news_task:
  description: >
    Conduct thorough research about the provided topic.
    Make sure you find any interesting and relevant information given.

  expected_output: >
    The list of 10 websites with the most relevant information about the topic.


website_scrape_task:
  description: >
    Scrape the website for the latest news and information

  expected_output: >
    Fully scraped websites with all the important information from the website.

ai_news_write_task:
  description: >
    Write the news article

  expected_output: >
    A fully fledge news article with the main topics, each with a full section of information.
    Formatted as markdown without '```'

file_write_task:
  description: >
    Convert the news article to a file

  expected_output: >
    A fully fledge news article with all information from previous task into a file named {date}_news_article.md