import { useState, useMemo, useCallback } from 'react';
import {
  Plus,
  PlayCircle,
  Clock,
  RefreshCw,
  Settings2,
  ChevronLeft,
  ChevronRight,
  Play,
  Loader2,
  Check,
  AlertTriangle,
} from 'lucide-react';
import { Button } from '../../components/ui/button';
import { useNavigate } from 'react-router';
import { OriginBadge } from '../../components/OriginBadge';
import {
  AutomationFilters,
  defaultFilters,
  hasActiveFilters,
  type AutomationFilterState,
} from '../../components/AutomationFilters';
import { mockWorkflows, mockCampaigns } from '../../data/mockData';
import type { Workflow } from '../../data/mockData';
import { useToast } from '../../components/ToastProvider';
import { useWorkflowFilter } from './WorkflowsLayout';
import { motion, AnimatePresence } from 'motion/react';

const PAGE_SIZE = 10;

export function AutomationsPage() {
  const sourceFilter = useWorkflowFilter();
  const [filters, setFilters] = useState<AutomationFilterState>(defaultFilters);
  const [currentPage, setCurrentPage] = useState(1);

  // All freeform workflows (before filters)
  const allFreeform = useMemo(() => {
    let items = mockWorkflows.filter(w => w.type === 'freeform');
    if (sourceFilter === 'custom') items = items.filter(w => !w.extensionId);
    if (sourceFilter === 'extension') items = items.filter(w => !!w.extensionId);
    return items;
  }, [sourceFilter]);

  // Derive filter options from the data
  const filterOptions = useMemo(() => {
    const goals = [...new Set(allFreeform.map(w => w.goal).filter(Boolean) as string[])].sort();
    const campaignIds = [...new Set(allFreeform.map(w => w.campaignId).filter(Boolean) as string[])];
    const campaigns = campaignIds
      .map(id => {
        const c = mockCampaigns.find(camp => camp.id === id);
        return c ? { id: c.id, name: c.name } : null;
      })
      .filter(Boolean) as { id: string; name: string }[];
    const tags = [...new Set(allFreeform.flatMap(w => w.tags || []))].sort();
    const statuses = [...new Set(allFreeform.map(w => w.status))].sort();
    const creators = [...new Set(allFreeform.map(w => w.createdBy).filter(Boolean) as string[])].sort();
    return { goals, campaigns, tags, statuses, creators };
  }, [allFreeform]);

  // Apply filters
  const filtered = useMemo(() => {
    let items = allFreeform;

    if (filters.goal) items = items.filter(w => w.goal === filters.goal);
    if (filters.campaignId) items = items.filter(w => w.campaignId === filters.campaignId);
    if (filters.tags.length > 0)
      items = items.filter(w => filters.tags.some(t => w.tags?.includes(t)));
    if (filters.status) items = items.filter(w => w.status === filters.status);
    if (filters.createdBy) items = items.filter(w => w.createdBy === filters.createdBy);
    if (filters.isActive === 'active') items = items.filter(w => w.isActive !== false);
    if (filters.isActive === 'inactive') items = items.filter(w => w.isActive === false);

    return items;
  }, [allFreeform, filters]);

  // Pagination
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const safePage = Math.min(currentPage, totalPages);
  const paginated = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);

  // Reset page when filters change
  const handleFilterChange = (newFilters: AutomationFilterState) => {
    setFilters(newFilters);
    setCurrentPage(1);
  };

  return (
    <div className="px-6 pb-6">
      {/* Description */}
      <div className="mb-4 p-4 rounded-[var(--radius-md)] bg-[var(--color-bg-elevated)] border border-[var(--color-border-default)]">
        <p className="text-sm text-muted-foreground">
          Schedule-driven workflows that run deterministic processes on the backend.
          Perfect for recurring tasks like daily reports, scheduled posts, or webhook-triggered actions.
          Automations can be generated by agents.
        </p>
      </div>

      {/* Filters + New button row */}
      <div className="flex items-start justify-between gap-4 mb-4">
        <div className="flex-1 min-w-0">
          <AutomationFilters
            filters={filters}
            onChange={handleFilterChange}
            options={filterOptions}
            totalResults={filtered.length}
            totalItems={allFreeform.length}
          />
        </div>
        <Button
          className="gap-2 shrink-0"
          style={{
            transitionTimingFunction: 'var(--ease-bounce)',
            transitionDuration: 'var(--duration-default)',
          }}
        >
          <Plus className="size-4" />
          New Project
        </Button>
      </div>

      {/* Automations List */}
      <div className="space-y-3">
        {paginated.map(wf => (
          <AutomationCard key={wf.id} workflow={wf} />
        ))}

        {filtered.length === 0 && (
          <div className="text-center py-12">
            <PlayCircle className="size-8 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">
              {hasActiveFilters(filters)
                ? 'No automations match your filters.'
                : sourceFilter === 'custom'
                  ? 'No custom automations yet.'
                  : sourceFilter === 'extension'
                    ? 'No extension-managed automations.'
                    : 'No automations created yet.'}
            </p>
            {hasActiveFilters(filters) ? (
              <Button
                variant="ghost"
                size="sm"
                className="mt-2 text-muted-foreground"
                onClick={() => handleFilterChange(defaultFilters)}
              >
                Clear all filters
              </Button>
            ) : (
              <p className="text-xs text-muted-foreground mt-1">
                Create automations to schedule recurring tasks, or let an agent generate one for you.
              </p>
            )}
          </div>
        )}
      </div>

      {/* Pagination */}
      {filtered.length > PAGE_SIZE && (
        <div className="flex items-center justify-between mt-6 pt-4 border-t border-[var(--color-border-default)]">
          <p className="text-xs text-muted-foreground">
            Showing {(safePage - 1) * PAGE_SIZE + 1}&ndash;{Math.min(safePage * PAGE_SIZE, filtered.length)} of {filtered.length}
          </p>
          <div className="flex items-center gap-1">
            <Button
              variant="outline"
              size="sm"
              disabled={safePage <= 1}
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              className="px-2"
            >
              <ChevronLeft className="size-4" />
            </Button>
            {generatePageNumbers(safePage, totalPages).map((page, i) =>
              page === '...' ? (
                <span key={`ellipsis-${i}`} className="px-2 text-xs text-muted-foreground">
                  ...
                </span>
              ) : (
                <Button
                  key={page}
                  variant={page === safePage ? 'default' : 'outline'}
                  size="sm"
                  className="min-w-[32px] px-2"
                  onClick={() => setCurrentPage(page as number)}
                >
                  {page}
                </Button>
              ),
            )}
            <Button
              variant="outline"
              size="sm"
              disabled={safePage >= totalPages}
              onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
              className="px-2"
            >
              <ChevronRight className="size-4" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Page number generator with ellipsis ───

function generatePageNumbers(
  current: number,
  total: number,
): (number | '...')[] {
  if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1);

  const pages: (number | '...')[] = [1];

  if (current > 3) pages.push('...');

  const start = Math.max(2, current - 1);
  const end = Math.min(total - 1, current + 1);

  for (let i = start; i <= end; i++) pages.push(i);

  if (current < total - 2) pages.push('...');

  pages.push(total);
  return pages;
}

// ─── Automation Card ───

function AutomationCard({ workflow }: { workflow: Workflow }) {
  const navigate = useNavigate();
  const { showToast } = useToast();
  const [runState, setRunState] = useState<'idle' | 'running' | 'done' | 'error'>('idle');

  const handleRun = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    if (runState !== 'idle') return;
    setRunState('running');

    // Simulate: ~70% success, ~30% failure
    const willSucceed = Math.random() > 0.3;
    setTimeout(() => {
      if (willSucceed) {
        setRunState('done');
        showToast(`"${workflow.name}" completed successfully`, { type: 'success' });
      } else {
        setRunState('error');
        showToast(`"${workflow.name}" failed — check logs for details`, {
          type: 'error',
          action: { label: 'View Details', onClick: () => navigate(`${workflow.id}`) },
        });
      }
      setTimeout(() => setRunState('idle'), 2000);
    }, 2500);
  }, [runState, workflow.name, showToast, navigate]);

  const buttonColor =
    runState === 'done'
      ? 'bg-emerald-500'
      : runState === 'error'
        ? 'bg-red-500'
        : 'bg-[var(--color-violet-500)] hover:bg-[var(--color-violet-600)]';

  const buttonShadow =
    runState === 'done'
      ? '0 2px 8px rgba(16, 185, 129, 0.4)'
      : runState === 'error'
        ? '0 2px 8px rgba(239, 68, 68, 0.4)'
        : 'var(--shadow-color-violet)';

  const borderClass =
    runState === 'running'
      ? 'border-[var(--color-violet-400)]'
      : runState === 'error'
        ? 'border-red-400'
        : 'border-[var(--color-border-default)] hover:border-[var(--color-border-strong)]';

  const cardShadow =
    runState === 'running'
      ? '0 0 16px rgba(139, 92, 246, 0.25)'
      : runState === 'error'
        ? '0 0 16px rgba(239, 68, 68, 0.15)'
        : undefined;

  return (
    <div
      className={`flex items-center gap-4 p-5 rounded-[var(--radius-md)] border-2 hover:-translate-y-0.5 transition-all cursor-pointer bg-card ${
        workflow.isActive === false ? 'opacity-60' : ''
      } ${borderClass}`}
      style={{
        transitionTimingFunction: 'var(--ease-bounce)',
        transitionDuration: 'var(--duration-fast)',
        ...(cardShadow ? { boxShadow: cardShadow } : {}),
      }}
    >
      <motion.div
        className={`size-10 rounded-[var(--radius-md)] flex items-center justify-center shrink-0 transition-colors ${buttonColor}`}
        style={{ boxShadow: buttonShadow }}
        role="button"
        tabIndex={0}
        title={
          runState === 'running' ? 'Running...'
            : runState === 'done' ? 'Complete'
            : runState === 'error' ? 'Failed'
            : 'Run automation'
        }
        onClick={handleRun}
        whileTap={runState === 'idle' ? { scale: 0.85 } : undefined}
        animate={
          runState === 'running'
            ? { scale: [1, 1.08, 1], transition: { repeat: Infinity, duration: 1.2, ease: 'easeInOut' } }
            : runState === 'done' || runState === 'error'
              ? { scale: [1.15, 1], transition: { duration: 0.3, ease: 'easeOut' } }
              : { scale: 1 }
        }
      >
        <AnimatePresence mode="wait">
          {runState === 'idle' && (
            <motion.span
              key="play"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.5 }}
              transition={{ duration: 0.15 }}
            >
              <Play className="size-5 text-[var(--color-text-inverse)] ml-0.5" fill="currentColor" />
            </motion.span>
          )}
          {runState === 'running' && (
            <motion.span
              key="loader"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1, rotate: 360 }}
              exit={{ opacity: 0, scale: 0.5 }}
              transition={{ rotate: { repeat: Infinity, duration: 0.8, ease: 'linear' }, opacity: { duration: 0.15 }, scale: { duration: 0.15 } }}
            >
              <Loader2 className="size-5 text-[var(--color-text-inverse)]" />
            </motion.span>
          )}
          {runState === 'done' && (
            <motion.span
              key="check"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.5 }}
              transition={{ duration: 0.15 }}
            >
              <Check className="size-5 text-[var(--color-text-inverse)]" />
            </motion.span>
          )}
          {runState === 'error' && (
            <motion.span
              key="error"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.5 }}
              transition={{ duration: 0.15 }}
            >
              <AlertTriangle className="size-5 text-[var(--color-text-inverse)]" />
            </motion.span>
          )}
        </AnimatePresence>
      </motion.div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1 flex-wrap">
          <p className="text-sm truncate">{workflow.name}</p>
          <OriginBadge extensionId={workflow.extensionId} />
          {workflow.isActive === false ? (
            <span className="text-[10px] px-1.5 py-0.5 rounded bg-[var(--color-error-bg)] text-[var(--color-error-text)]">
              Inactive
            </span>
          ) : (
            <span className="text-[10px] px-1.5 py-0.5 rounded bg-[var(--color-success-bg)] text-[var(--color-success-text)]">
              Active
            </span>
          )}
        </div>
      </div>

      <div className="shrink-0 text-right space-y-1">
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground justify-end">
          <Clock className="size-3" />
          {workflow.schedule}
        </div>
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground justify-end">
          <RefreshCw className="size-3" />
          Last run: {workflow.lastRun.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} at{' '}
          {workflow.lastRun.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </div>
      </div>

      <div className="flex items-center gap-2 shrink-0">
        <Button variant="outline" size="sm" onClick={() => navigate(`${workflow.id}`)}>
          <Settings2 className="size-3.5 mr-1" />
          Configure
        </Button>
      </div>
    </div>
  );
}