"""
Tests for MarketingGraphBuilder.

This module tests the marketing graph construction functionality,
ensuring that marketing research reports are correctly converted
into Neo4j graph nodes and relationships.
"""

import pytest
from unittest.mock import Mock

# Use relative imports to work both in tests and when deployed
try:
    # Try relative import first (for when running in Agent Engine)
    from ..marketing_graph_builder import MarketingGraphBuilder
    from ..marketing_models import (
        MarketingResearchReport,
        IdealCustomerProfile,
        ProductCategoryMapping,
        CustomerStrategy,
        MarketingStrategy,
    )
except ImportError:
    # Fall back to absolute import (for when running tests from root)
    from agents.strategy_agent.marketing_graph_builder import MarketingGraphBuilder
    from agents.strategy_agent.marketing_models import (
        MarketingResearchReport,
        IdealCustomerProfile,
        ProductCategoryMapping,
        CustomerStrategy,
        MarketingStrategy,
    )


@pytest.fixture
def mock_neo4j_ops():
    """Create a mock Neo4j operations instance."""
    mock = Mock()
    mock.connection = Mock()
    return mock


@pytest.fixture
def graph_builder(mock_neo4j_ops):
    """Create a MarketingGraphBuilder instance with mocked Neo4j ops."""
    return MarketingGraphBuilder(mock_neo4j_ops)


@pytest.fixture
def sample_marketing_report():
    """
    Create a sample marketing research report matching the Bank of America example.

    This fixture represents the actual data structure generated by the marketing
    formatter agent, including multiple customer profiles and product categories.
    """
    return MarketingResearchReport(
        ideal_customer_profiles=[
            IdealCustomerProfile(
                display_name="Student Steve",
                narrative="Steve is a 20-year-old full-time university student...",
                references=[
                    "https://www.ey.com/en_gl/banking-capital-markets/how-banks-can-build-stronger-relationships-with-gen-z",
                ],
            ),
            IdealCustomerProfile(
                display_name="Middle-Class Maria",
                narrative="Maria is a 42-year-old marketing manager...",
                references=[
                    "https://www.forbes.com/advisor/banking/state-of-banking-2024/",
                ],
            ),
            IdealCustomerProfile(
                display_name="Small Business Owner Sam",
                narrative="Sam is a 48-year-old who owns a growing local chain...",
                references=[
                    "https://www.jpmorganchase.com/institute/research/small-business/small-business-banking-relationships",
                ],
            ),
            IdealCustomerProfile(
                display_name="High-Net-Worth Helen",
                narrative="Helen is a 62-year-old retired surgeon...",
                references=[
                    "https://www.capgemini.com/us-en/research/world-wealth-report/",
                ],
            ),
        ],
        product_category_mappings=[
            ProductCategoryMapping(
                category_name="Consumer Banking",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="Student Steve",
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="Many students are unaware...",
                            brand_awareness_strategy="Introduce Bank of America...",
                            consideration_strategy="Steve compares banking options...",
                            conversion_strategy="Conversion for Steve is a quick...",
                            loyalty_strategy="Loyalty is built by providing...",
                            references=[
                                "https://www.ey.com/en_gl/banking-capital-markets/how-banks-can-build-stronger-relationships-with-gen-z",
                            ],
                        ),
                    ),
                    CustomerStrategy(
                        customer_profile_name="Middle-Class Maria",
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="Maria's problem isn't...",
                            brand_awareness_strategy="Position Bank of America...",
                            consideration_strategy="Maria evaluates banks...",
                            conversion_strategy="Conversion involves moving...",
                            loyalty_strategy="Loyalty is retained through...",
                            references=[
                                "https://www.forbes.com/advisor/banking/state-of-banking-2024/",
                            ],
                        ),
                    ),
                ],
            ),
            ProductCategoryMapping(
                category_name="Business Banking",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="Small Business Owner Sam",
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="Sam's biggest problems...",
                            brand_awareness_strategy="Position Bank of America...",
                            consideration_strategy="Sam evaluates banks...",
                            conversion_strategy="The conversion action is...",
                            loyalty_strategy="Loyalty is built on a strong...",
                            references=[
                                "https://www.jpmorganchase.com/institute/research/small-business/small-business-banking-relationships",
                            ],
                        ),
                    ),
                ],
            ),
            ProductCategoryMapping(
                category_name="Wealth Management and Institutional Services",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="High-Net-Worth Helen",
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="Helen is aware she needs...",
                            brand_awareness_strategy="Position Bank of America's...",
                            consideration_strategy="Helen will not be swayed...",
                            conversion_strategy="Conversion is a long-term...",
                            loyalty_strategy="Loyalty for Helen is the...",
                            references=[
                                "https://www.capgemini.com/us-en/research/world-wealth-report/",
                            ],
                        ),
                    ),
                ],
            ),
        ],
    )


def test_build_marketing_graph_with_valid_product_categories(
    graph_builder, mock_neo4j_ops, sample_marketing_report
):
    """
    Test that build_marketing_graph correctly processes a valid marketing report.

    This test verifies the fix for the KeyError: 0 bug that occurred when
    incorrectly indexing Neo4j query results. The bug was in the
    _get_product_category_node_id method which incorrectly treated the
    result as result[0][0]["node_id"] instead of result[0]["node_id"].

    Test coverage:
    - All customer profiles are created as master CustomerProfile nodes
    - Product categories are looked up correctly in Neo4j
    - Strategy nodes are created for each valid customer/product mapping
    - Relationships are established between profiles, strategies, and products
    """
    account_id = "test_acc_123"

    # Mock Neo4j responses for product category lookups
    # The execute_query method returns [{"node_id": "..."}] format
    mock_neo4j_ops.connection.execute_query.side_effect = [
        # First call: Consumer Banking lookup
        [{"node_id": "prod_consumer_banking_001"}],
        # Second call: Business Banking lookup
        [{"node_id": "prod_business_banking_002"}],
        # Third call: Wealth Management lookup
        [{"node_id": "prod_wealth_management_003"}],
    ]

    # Mock the _create_customer_profile_node method
    profile_node_ids = {
        "Student Steve": "profile_student_steve_001",
        "Middle-Class Maria": "profile_maria_002",
        "Small Business Owner Sam": "profile_sam_003",
        "High-Net-Worth Helen": "profile_helen_004",
    }

    original_create_profile = graph_builder._create_customer_profile_node

    def mock_create_profile(profile, account_id):
        return profile_node_ids[profile.display_name]

    graph_builder._create_customer_profile_node = mock_create_profile

    # Mock the _create_strategy_nodes_for_customer method
    created_strategies = []

    def mock_create_strategies(
        profile_node_id, customer_strategy, product_category_id, account_id
    ):
        created_strategies.append(
            {
                "profile_node_id": profile_node_id,
                "customer_profile_name": customer_strategy.customer_profile_name,
                "product_category_id": product_category_id,
            }
        )

    graph_builder._create_strategy_nodes_for_customer = mock_create_strategies

    # Execute
    graph_builder.build_marketing_graph(sample_marketing_report, account_id)

    # Verify customer profiles were created
    expected_profile_count = len(sample_marketing_report.ideal_customer_profiles)
    assert len(profile_node_ids) == expected_profile_count

    # Verify product category lookups were called correctly
    expected_category_count = len(sample_marketing_report.product_category_mappings)
    assert mock_neo4j_ops.connection.execute_query.call_count == expected_category_count

    # Verify the query structure for product category lookups
    first_call = mock_neo4j_ops.connection.execute_query.call_args_list[0]
    query = first_call[0][0]
    params = first_call[0][1]

    assert "MATCH (pc:ProductCategory)" in query
    assert "BELONGS_TO" in query
    assert "Account" in query
    assert params["account_id"] == account_id
    assert params["category_name"] == "Consumer Banking"

    # Verify strategies were created for all valid mappings
    expected_strategy_count = sum(
        len(mapping.customer_strategies)
        for mapping in sample_marketing_report.product_category_mappings
    )
    assert len(created_strategies) == expected_strategy_count

    # Verify Student Steve strategies
    steve_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "Student Steve"
    ]
    assert len(steve_strategies) == 1
    assert steve_strategies[0]["profile_node_id"] == "profile_student_steve_001"
    assert steve_strategies[0]["product_category_id"] == "prod_consumer_banking_001"

    # Verify Middle-Class Maria strategies
    maria_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "Middle-Class Maria"
    ]
    assert len(maria_strategies) == 1
    assert maria_strategies[0]["profile_node_id"] == "profile_maria_002"
    assert maria_strategies[0]["product_category_id"] == "prod_consumer_banking_001"

    # Verify Small Business Owner Sam strategies
    sam_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "Small Business Owner Sam"
    ]
    assert len(sam_strategies) == 1
    assert sam_strategies[0]["profile_node_id"] == "profile_sam_003"
    assert sam_strategies[0]["product_category_id"] == "prod_business_banking_002"

    # Verify High-Net-Worth Helen strategies
    helen_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "High-Net-Worth Helen"
    ]
    assert len(helen_strategies) == 1
    assert helen_strategies[0]["profile_node_id"] == "profile_helen_004"
    assert helen_strategies[0]["product_category_id"] == "prod_wealth_management_003"


def test_get_product_category_node_id_returns_correct_value(
    graph_builder, mock_neo4j_ops
):
    """
    Test that _get_product_category_node_id correctly parses Neo4j results.

    This test specifically verifies the fix for the KeyError: 0 bug.
    The bug occurred because the code incorrectly assumed Neo4j's execute_query
    returns [[{"node_id": "..."}]] but it actually returns [{"node_id": "..."}].

    The incorrect code was:
        if result and len(result[0]) > 0:
            return result[0][0]["node_id"]

    The correct code is:
        if result and len(result) > 0:
            return result[0]["node_id"]
    """
    account_id = "test_acc_456"
    category_name = "Consumer Banking"
    expected_node_id = "prod_consumer_banking_xyz"

    # Mock Neo4j response in the correct format: [{"node_id": "..."}]
    mock_neo4j_ops.connection.execute_query.return_value = [
        {"node_id": expected_node_id}
    ]

    # Execute
    result = graph_builder._get_product_category_node_id(category_name, account_id)

    # Verify
    assert result == expected_node_id

    # Verify the query was called with correct parameters
    call_args = mock_neo4j_ops.connection.execute_query.call_args
    query = call_args[0][0]
    params = call_args[0][1]

    assert "MATCH (pc:ProductCategory)" in query
    assert params["account_id"] == account_id
    assert params["category_name"] == category_name


def test_get_product_category_node_id_handles_not_found(
    graph_builder, mock_neo4j_ops
):
    """
    Test that _get_product_category_node_id returns None when category not found.

    This test verifies the method handles empty result sets correctly,
    which was part of the bug fix validation.
    """
    account_id = "test_acc_789"
    category_name = "Nonexistent Category"

    # Mock Neo4j response: empty result
    mock_neo4j_ops.connection.execute_query.return_value = []

    # Execute
    result = graph_builder._get_product_category_node_id(category_name, account_id)

    # Verify
    assert result is None


def test_build_marketing_graph_skips_invalid_product_categories(
    graph_builder, mock_neo4j_ops, sample_marketing_report
):
    """
    Test that build_marketing_graph gracefully skips product categories not in Neo4j.

    This test verifies the behavior when a product category name from the
    marketing formatter doesn't match any ProductCategory node in Neo4j.
    The system should log a warning and skip creating strategies for that
    product category, but continue processing other valid categories.
    """
    account_id = "test_acc_999"

    # Mock Neo4j responses: first category not found, others found
    mock_neo4j_ops.connection.execute_query.side_effect = [
        # First call: Consumer Banking not found
        [],
        # Second call: Business Banking found
        [{"node_id": "prod_business_banking_002"}],
        # Third call: Wealth Management found
        [{"node_id": "prod_wealth_management_003"}],
    ]

    # Mock profile creation
    profile_node_ids = {
        "Student Steve": "profile_student_steve_001",
        "Middle-Class Maria": "profile_maria_002",
        "Small Business Owner Sam": "profile_sam_003",
        "High-Net-Worth Helen": "profile_helen_004",
    }

    def mock_create_profile(profile, account_id):
        return profile_node_ids[profile.display_name]

    graph_builder._create_customer_profile_node = mock_create_profile

    # Mock strategy creation
    created_strategies = []

    def mock_create_strategies(
        profile_node_id, customer_strategy, product_category_id, account_id
    ):
        created_strategies.append(
            {
                "profile_node_id": profile_node_id,
                "customer_profile_name": customer_strategy.customer_profile_name,
                "product_category_id": product_category_id,
            }
        )

    graph_builder._create_strategy_nodes_for_customer = mock_create_strategies

    # Execute
    graph_builder.build_marketing_graph(sample_marketing_report, account_id)

    # Verify: Only strategies for Business Banking and Wealth Management were created
    # Consumer Banking strategies (Student Steve and Maria) should be skipped
    # Calculate expected count: mappings[1] (Business Banking) + mappings[2] (Wealth Management)
    expected_strategies = sum(
        len(mapping.customer_strategies)
        for mapping in sample_marketing_report.product_category_mappings[1:]  # Skip first (Consumer Banking)
    )
    assert len(created_strategies) == expected_strategies

    # Verify Sam's strategy was created
    sam_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "Small Business Owner Sam"
    ]
    assert len(sam_strategies) == 1

    # Verify Helen's strategy was created
    helen_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "High-Net-Worth Helen"
    ]
    assert len(helen_strategies) == 1

    # Verify Student Steve and Maria strategies were NOT created
    steve_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "Student Steve"
    ]
    assert len(steve_strategies) == 0

    maria_strategies = [
        s
        for s in created_strategies
        if s["customer_profile_name"] == "Middle-Class Maria"
    ]
    assert len(maria_strategies) == 0


def test_link_product_category_to_customer_profile_returns_correct_value(
    graph_builder, mock_neo4j_ops
):
    """
    Test that _link_product_category_to_customer_profile correctly parses Neo4j results.

    This test verifies the fix for the SECOND occurrence of the KeyError: 0 bug.
    The bug was in the same pattern as _get_product_category_node_id, where the
    code incorrectly assumed Neo4j returns [[{...}]] instead of [{...}].

    Bug location: marketing_graph_builder.py line 524-528
    """
    product_category_id = "prod_banking_001"
    customer_profile_id = "profile_steve_001"
    account_id = "test_acc_456"

    # Mock Neo4j response in the correct format: [{"category": "...", "profile": "..."}]
    mock_neo4j_ops.connection.execute_query.return_value = [
        {"category": "Consumer Banking", "profile": customer_profile_id}
    ]

    # Execute
    result = graph_builder._link_product_category_to_customer_profile(
        product_category_id, customer_profile_id, account_id
    )

    # Verify
    assert result is not None
    assert result["category"] == "Consumer Banking"
    assert result["profile"] == customer_profile_id

    # Verify the query was called with correct parameters
    call_args = mock_neo4j_ops.connection.execute_query.call_args
    query = call_args[0][0]
    params = call_args[0][1]

    assert "MATCH (pc:ProductCategory" in query
    assert "MATCH (cp:CustomerProfile" in query
    assert "IS_MARKETED_TO" in query
    assert params["category_id"] == product_category_id
    assert params["profile_id"] == customer_profile_id


def test_link_product_category_to_customer_profile_handles_failure(
    graph_builder, mock_neo4j_ops
):
    """
    Test that _link_product_category_to_customer_profile returns None on failure.

    This verifies proper handling of empty results when the link cannot be created
    (e.g., when one of the nodes doesn't exist).
    """
    product_category_id = "prod_nonexistent_001"
    customer_profile_id = "profile_steve_001"
    account_id = "test_acc_789"

    # Mock Neo4j response: empty result (nodes not found or link failed)
    mock_neo4j_ops.connection.execute_query.return_value = []

    # Execute
    result = graph_builder._link_product_category_to_customer_profile(
        product_category_id, customer_profile_id, account_id
    )

    # Verify
    assert result is None


def test_customer_profile_includes_display_name(graph_builder, mock_neo4j_ops):
    """
    Test that _create_customer_profile passes display_name to Neo4j.

    This verifies the enhancement where display_name is added to the node_data
    on line 235 of marketing_graph_builder.py. The display_name should be
    lowercased and passed as a property to the Neo4j CustomerProfile node.

    Validates:
    1. display_name is included in node_data
    2. display_name is lowercased
    3. display_name is passed to neo4j_ops.create_strategy_node
    """
    account_id = "test_acc_123"

    # Create test customer profile with display_name
    test_profile = IdealCustomerProfile(
        display_name="Recent Graduate Rachel",
        narrative="Rachel is a 23-year-old who recently graduated...",
        references=["https://example.com/ref1"],
    )

    # Mock the create_strategy_node method to capture the call
    mock_neo4j_ops.create_strategy_node = Mock(
        return_value={"node_id": "icp_test_123", "display_name": "recent graduate rachel"}
    )

    # Execute
    result = graph_builder._create_customer_profile(test_profile, account_id)

    # Verify create_strategy_node was called
    assert mock_neo4j_ops.create_strategy_node.called
    call_args = mock_neo4j_ops.create_strategy_node.call_args

    # Verify the arguments: (node_type, node_data, account_id)
    node_type = call_args[0][0]
    node_data = call_args[0][1]
    passed_account_id = call_args[0][2]

    # Verify node type
    assert node_type == "CustomerProfile"

    # Verify account_id
    assert passed_account_id == account_id

    # Verify node_data contains display_name
    assert "display_name" in node_data
    assert node_data["display_name"] == "recent graduate rachel"  # Lowercased

    # Verify other expected fields
    assert "node_id" in node_data
    assert "description" in node_data
    assert node_data["description"] == test_profile.narrative
    assert "references" in node_data
    assert node_data["references"] == test_profile.references


def test_display_name_lowercasing(graph_builder, mock_neo4j_ops):
    """
    Test that display_name is properly lowercased.

    This ensures consistent querying and comparison of customer profiles
    in Neo4j regardless of the original casing from the LLM.
    """
    account_id = "test_acc_456"

    test_cases = [
        ("Family Manager Frank", "family manager frank"),
        ("SMALL BUSINESS OWNER SARAH", "small business owner sarah"),
        ("High Net Worth Henry", "high net worth henry"),
        ("MiXeD CaSe NaMe", "mixed case name"),
    ]

    mock_neo4j_ops.create_strategy_node = Mock(return_value={"node_id": "test_id"})

    for original_name, expected_lowercase in test_cases:
        test_profile = IdealCustomerProfile(
            display_name=original_name,
            narrative="Test narrative",
            references=[],
        )

        # Execute
        graph_builder._create_customer_profile(test_profile, account_id)

        # Get the last call's arguments
        call_args = mock_neo4j_ops.create_strategy_node.call_args
        node_data = call_args[0][1]

        # Verify lowercasing
        assert node_data["display_name"] == expected_lowercase


def test_build_graph_with_nonexistent_profile_reference(
    graph_builder, mock_neo4j_ops
):
    """
    Test that build_marketing_graph raises ValueError when a customer strategy
    references a profile that doesn't exist in the master profile list.

    This validates the strategy count validation that detects skipped profiles.
    """
    account_id = "test_acc_123"

    # Create report with profile reference mismatch
    report = MarketingResearchReport(
        ideal_customer_profiles=[
            IdealCustomerProfile(
                display_name="Student Steve",
                narrative="Steve is a student...",
                references=[],
            ),
        ],
        product_category_mappings=[
            ProductCategoryMapping(
                category_name="Consumer Banking",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="Non-Existent Profile",  # Mismatch!
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="Strategy text...",
                            brand_awareness_strategy="Strategy text...",
                            consideration_strategy="Strategy text...",
                            conversion_strategy="Strategy text...",
                            loyalty_strategy="Strategy text...",
                            references=[],
                        ),
                    ),
                ],
            ),
        ],
    )

    # Mock Neo4j to return a valid product category
    mock_neo4j_ops.connection.execute_query.return_value = [
        {"node_id": "prod_consumer_banking_001"}
    ]
    mock_neo4j_ops.create_strategy_node = Mock()

    # Execute and expect ValueError
    with pytest.raises(ValueError) as exc_info:
        graph_builder.build_marketing_graph(report, account_id, "user_123")

    # Verify error message contains details
    error_msg = str(exc_info.value)
    assert "Strategy count mismatch" in error_msg
    assert "expected 1" in error_msg
    assert "created 0" in error_msg
    assert "Non-Existent Profile" in error_msg


def test_build_graph_with_all_strategies_skipped(
    graph_builder, mock_neo4j_ops
):
    """
    Test that build_marketing_graph raises ValueError when all strategies
    are skipped due to profile name mismatches.
    """
    account_id = "test_acc_456"

    # Create report where NO profiles match
    report = MarketingResearchReport(
        ideal_customer_profiles=[
            IdealCustomerProfile(
                display_name="Student Steve",
                narrative="Steve is a student...",
                references=[],
            ),
            IdealCustomerProfile(
                display_name="Business Owner Beth",
                narrative="Beth owns a business...",
                references=[],
            ),
        ],
        product_category_mappings=[
            ProductCategoryMapping(
                category_name="Consumer Banking",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="Wrong Name 1",
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="...",
                            brand_awareness_strategy="...",
                            consideration_strategy="...",
                            conversion_strategy="...",
                            loyalty_strategy="...",
                            references=[],
                        ),
                    ),
                ],
            ),
            ProductCategoryMapping(
                category_name="Business Banking",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="Wrong Name 2",
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="...",
                            brand_awareness_strategy="...",
                            consideration_strategy="...",
                            conversion_strategy="...",
                            loyalty_strategy="...",
                            references=[],
                        ),
                    ),
                ],
            ),
        ],
    )

    # Mock Neo4j to return valid product categories
    mock_neo4j_ops.connection.execute_query.side_effect = [
        [{"node_id": "prod_consumer_001"}],
        [{"node_id": "prod_business_002"}],
    ]
    mock_neo4j_ops.create_strategy_node = Mock()

    # Execute and expect ValueError
    with pytest.raises(ValueError) as exc_info:
        graph_builder.build_marketing_graph(report, account_id, "user_456")

    # Verify error contains both skipped profiles
    error_msg = str(exc_info.value)
    assert "expected 2" in error_msg
    assert "created 0" in error_msg
    assert "Skipped 2 profile references" in error_msg
    assert "Wrong Name 1" in error_msg
    assert "Wrong Name 2" in error_msg


def test_build_graph_with_partial_profile_matches(
    graph_builder, mock_neo4j_ops
):
    """
    Test that build_marketing_graph raises ValueError when some (but not all)
    profile references don't match, providing detailed error information.
    """
    account_id = "test_acc_789"

    # Create report with mix of valid and invalid references
    report = MarketingResearchReport(
        ideal_customer_profiles=[
            IdealCustomerProfile(
                display_name="Student Steve",
                narrative="Steve is a student...",
                references=[],
            ),
        ],
        product_category_mappings=[
            ProductCategoryMapping(
                category_name="Consumer Banking",
                customer_strategies=[
                    CustomerStrategy(
                        customer_profile_name="Student Steve",  # Valid
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="...",
                            brand_awareness_strategy="...",
                            consideration_strategy="...",
                            conversion_strategy="...",
                            loyalty_strategy="...",
                            references=[],
                        ),
                    ),
                    CustomerStrategy(
                        customer_profile_name="Invalid Profile",  # Invalid
                        strategy=MarketingStrategy(
                            problem_awareness_strategy="...",
                            brand_awareness_strategy="...",
                            consideration_strategy="...",
                            conversion_strategy="...",
                            loyalty_strategy="...",
                            references=[],
                        ),
                    ),
                ],
            ),
        ],
    )

    # Mock Neo4j responses
    mock_neo4j_ops.connection.execute_query.return_value = [
        {"node_id": "prod_consumer_001"}
    ]
    mock_neo4j_ops.create_strategy_node = Mock()

    # Execute and expect ValueError
    with pytest.raises(ValueError) as exc_info:
        graph_builder.build_marketing_graph(report, account_id, "user_789")

    # Verify error shows partial success
    error_msg = str(exc_info.value)
    assert "expected 2" in error_msg
    assert "created 1" in error_msg
    assert "Skipped 1 profile references" in error_msg
    assert "Invalid Profile" in error_msg
