"""Shared token-accounting helper for the KEN-E agentic harness.

Owner: Billing (BL-PRD-02). Chat consumes. Changes require Billing review.
Ownership transfers on BL-PRD-02 merge. No changes to this file without
Billing review.

Both Chat's per-turn SessionTurnAccumulator (CH-PRD-01) and Billing's
monthly token meter (BL-PRD-02) count tokens against the same definition:
  input + output + reasoning, excluding the cached-input discount.

This single helper ensures divergence is impossible by construction — any
change to the token definition is applied once here and reflected in both
consumers simultaneously.

Parity test: api/tests/unit/chat/test_token_accounting_parity.py pins the
canonical fixture (prompt=1250, cached=200, candidates=380, thoughts=0 →
input=1050, output=380, reasoning=0, total_billable=1430). BL-PRD-02's
duplicated copy in api/tests/unit/billing/ must anchor on these same numbers.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class BillableTokenCounts(BaseModel):
    """Billable token counts extracted from an ADK event.

    The three fields sum to `total_billable`. Cached-input tokens are
    deliberately excluded — they represent KEN-E margin, not customer cost.

    Owner: Billing (BL-PRD-02). Chat consumes. Changes require Billing review.
    """

    input: int = Field(default=0, ge=0, description="Prompt tokens minus cached-input tokens")
    output: int = Field(default=0, ge=0, description="Completion tokens generated by the model")
    reasoning: int = Field(default=0, ge=0, description="Internal reasoning tokens (0 for non-reasoning models)")

    @property
    def total_billable(self) -> int:
        """Sum of input + output + reasoning."""
        return self.input + self.output + self.reasoning


def extract_billable_tokens(event: Any) -> BillableTokenCounts:
    """Extract billable token counts from an ADK event.

    Token definition (invariant, shared with Billing — do not change without
    Billing review):
      - input  = prompt_token_count - cached_content_token_count  (floor 0)
      - output = candidates_token_count
      - reasoning = thoughts_token_count  (0 for non-reasoning models)
      - cached_content_token_count is EXCLUDED (KEN-E margin, not customer cost)

    Returns BillableTokenCounts(input=0, output=0, reasoning=0) when
    event.usage_metadata is absent or falsy.

    Args:
        event: Any ADK event object. Accessed via duck-typing so the function
               works without importing ADK's internal Event type.

    Returns:
        BillableTokenCounts with non-negative integer fields.
    """
    usage = getattr(event, "usage_metadata", None)
    if usage is None:
        return BillableTokenCounts()

    # int() casts guard against silent float/string coercion in Pydantic v2.
    # Both getattr default and `or 0` handle missing/None fields from SDK.
    prompt: int = int(getattr(usage, "prompt_token_count", 0) or 0)
    candidates: int = int(getattr(usage, "candidates_token_count", 0) or 0)
    thoughts: int = int(getattr(usage, "thoughts_token_count", 0) or 0)
    cached: int = int(getattr(usage, "cached_content_token_count", 0) or 0)

    return BillableTokenCounts(
        input=max(0, prompt - cached),
        output=candidates,
        reasoning=thoughts,
    )
