// This file provides shared KPI data derived from the metrics in MetricsPage.tsx
// Import the initialMetrics from MetricsPage to keep data in sync

// Note: We can't directly import from MetricsPage due to circular dependency issues,
// so we'll recreate the metric names here. In a real app, this would be in a shared data file.

const metricNames = [
  "Engaged Sessions",
  "Transactions",
  "Total Users",
  "New Users",
  "Sessions",
  "Page Views",
  "Bounce Rate",
  "Average Session Duration",
  "Conversion Rate",
  "Revenue",
  "Average Order Value",
  "Add to Cart Events",
  "Checkout Events",
  "Event Count",
  "Unique Events",
  "Sessions per User",
  "Engagement Rate",
  "Pages per Session",
  "Scroll Events",
  "File Downloads",
  "Video Start Events",
  "Search Events",
];

// For KPI dropdowns, we want to include both our Google Analytics metrics
// and some additional common marketing KPIs
export const availableKPIs = [
  // Google Analytics metrics from initialMetrics
  ...metricNames,
  // Additional common marketing KPIs
  "Total Prospect Impressions",
  "Total Media CPM",
  "Click-Through Rate",
  "Cost Per Click",
  "Cost Per Acquisition",
  "Return on Ad Spend",
  "Brand Awareness Lift",
  "Reach",
  "Frequency",
  "Lead Quality Score",
  "Customer Lifetime Value",
  "Retention Cost",
  "Email Open Rate",
  "Cost Per Send",
  "View-Through Rate",
  "Cost Per Impression",
  "Video Completion Rate",
  "Cost Per View",
  "Organic Reach",
  "Cost Per Post",
  "Social Conversion Rate",
  "Cost Per Social Click",
  "Search Conversion Rate",
  "Organic Click Rate",
  "Cost Per Organic Session",
  "Email Click Rate",
  "Event Attendance Rate",
  "Cost Per Attendee",
  "Cost Per Engagement",
  "Professional Reach",
  "Cost Per Professional Click",
  "Content Engagement Rate",
  "Cost Per Content View",
  "Sponsored Post Engagement",
  "Cost Per Sponsored Engagement",
  "Organic Search Visibility",
  "Cost Per Discovery",
  "Trial Conversion Rate",
  "Cost Per Trial User",
  "Activation Rate",
  "Cost Per Activated User",
  "Trial to Paid Conversion",
  "Customer Acquisition Cost",
  "Launch Day Ranking",
  "Cost Per Hunter",
  "Tech Blog Mentions",
  "Cost Per Tech Mention",
  "Industry Recognition",
  "Cost Per Industry Impression",
  "Consultation Request Rate",
  "Cost Per Consultation",
  "Proposal Win Rate",
  "Cost Per Proposal",
  "Client Retention Rate",
  "Cost Per Retained Client",
  "Case Study Views",
  "Cost Per Case Study View",
  "Event Lead Quality",
  "Cost Per Event Lead",
];

export default availableKPIs;
